services:
  - type: web
    name: buddybot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: WEB_CONCURRENCY
        value: "1"
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MURF_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /
        destination: /
    healthCheckPath: /health
